### ISSUE TITLE
Hilt can't find binding for CardRepository

### ISSUE THREAD

**Issue by IkemNwodo** [IkemNwodo/CardInfoFinder#1]
Hilt can't find binding for the Repository interface that's injected into useCase class in the domain module.

The Repository interface is in the domain module while it is provided in the data module. When I try to build, I get error showing that binding for Repository is missing.
@karandhillon

**Comment by karandhillon** [comment]
Can you please include the Module files as well as the stack trace here @IkemNwodo ? thank you!

**Comment by IkemNwodo** [comment]
`C:\Users\Ikem\AndroidStudioProjects\CardInfoFinder\app\build\generated\source\kapt\debug\com\bankwithmit\cardinfofinder\App_HiltComponents.java:152: error: [Dagger/MissingBinding] com.bankwithmit.domain.repositories.CardRepository cannot be provided without an @Provides-annotated method.
  public abstract static class ApplicationC implements App_GeneratedInjector,
                         ^
      com.bankwithmit.domain.repositories.CardRepository is injected at
          com.bankwithmit.domain.usecases.GetCardInfoUsecase(repository)
      javax.inject.Provider<com.bankwithmit.domain.usecases.GetCardInfoUsecase> is injected at
          com.bankwithmit.cardinfofinder.ui.result.ResultViewModel_AssistedFactory(getCardInfoUsecase)
      com.bankwithmit.cardinfofinder.ui.result.ResultViewModel_AssistedFactory is injected at
          com.bankwithmit.cardinfofinder.ui.result.ResultViewModel_HiltModule.bind(factory)
      java.util.Map<java.lang.String,javax.inject.Provider<androidx.hilt.lifecycle.ViewModelAssistedFactory<? extends androidx.lifecycle.ViewModel>>> is injected at
          androidx.hilt.lifecycle.ViewModelFactoryModules.ActivityModule.provideFactory(�, viewModelFactories)
      @dagger.hilt.android.internal.lifecycle.DefaultActivityViewModelFactory java.util.Set<androidx.lifecycle.ViewModelProvider.Factory> is requested at
          dagger.hilt.android.internal.lifecycle.DefaultViewModelFactories.ActivityEntryPoint.getActivityViewModelFactory() [com.bankwithmit.cardinfofinder.App_HiltComponents.ApplicationC ? com.bankwithmit.cardinfofinder.App_HiltComponents.ActivityRetainedC ? com.bankwithmit.cardinfofinder.App_HiltComponents.ActivityC]
  The following other entry points also depend on it:
      dagger.hilt.android.internal.lifecycle.DefaultViewModelFactories.FragmentEntryPoint.getFragmentViewModelFactory() [com.bankwithmit.cardinfofinder.App_HiltComponents.ApplicationC ? com.bankwithmit.cardinfofinder.App_HiltComponents.ActivityRetainedC ? com.bankwithmit.cardinfofinder.App_HiltComponents.ActivityC ? com.bankwithmit.cardinfofinder.App_HiltComponents.FragmentC]`
@karanDhillon

**Comment by karandhillon** [comment]
Please format the stack trace using three ` characters.

**Comment by IkemNwodo** [comment]
> Please format the stack trace using three ` characters.

I did. Probably screenshot would be more clearer
![Screenshot (9)](https://user-images.githubusercontent.com/21228864/107297466-5381ea00-6a6b-11eb-98de-a6d8f2ad8059.png)

**Comment by karandhillon** [comment]
Can you please post the `Module` file where you have defined the `CardRepository` dependency? thanks!

**Comment by IkemNwodo** [comment]
> Can you please post the `Module` file where you have defined the `CardRepository` dependency? thanks!

Sure! 
https://github.com/IkemNwodo/CardInfoFinder/blob/master/domain/src/main/java/com/bankwithmit/domain/repositories/CardRepository.kt

**Comment by karandhillon** [comment]
I mean the Hilt module, which provides the `CardRepository` please. thank you!

**Comment by IkemNwodo** [comment]
> I mean the Hilt module, which provides the `CardRepository` please. thank you!

Oh, okay.
Here:

**Comment by IkemNwodo** [comment]
https://github.com/IkemNwodo/CardInfoFinder/blob/master/data/src/main/java/com/bankwithmit/data/di/RepositoryModule.kt

> I mean the Hilt module, which provides the `CardRepository` please. thank you!

**Comment by karandhillon** [comment]
@IkemNwodo you should write down how you fixed the issue here, and then close this issue. Good job 👍🏻

**Comment by IkemNwodo** [comment]
With the help of @princessdharmy I was able to fix this issue.
The domain and data modules were missing the "Kotlin-kapt" plugin, and also the dagger hilt dependencies. The hilt compiler in the data module was added with implementation instead of kapt

Thanks @karanDhillon for the time you've spent trying to get this issue resolved. And also @princessdharmy, thank you!
